displayName=Looting Bag Loot Tracker
author=Austin Baker
description=Tracks loot that goes into an open looting bag during chest and container interactions
tags=loot,tracker,looting bag,thieving,chest,rogues,bag,wilderness,
plugins=com.lootingbagtracker.LootingBagTrackerPlugin
